service: quiztopia-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  profile: ${env:PROFILE}
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct
  environment:
    DYNAMODB_USERS_TABLE: QuizUsersDb
    DYNAMODB_USER_INDEX: userNameIndex
    DYNAMODB_QUIZ_TABLE: QuizTable
    DYNAMODB_CREATOR_INDEX: creatorIDIndex
    DYNAMODB_QUESTION_TABLE: questionTable
    DYNAMODB_QUESTION_INDEX: quizIdIndex
    DYNAMODB_REGION: 'eu-north-1'
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

package:
  individually: true

functions:
  signUpUser:
    handler: src/functions/signUpUser.handler
    events:
      - httpApi:
          path: '/api/signup'
          method: POST
  signInUser:
    handler: src/functions/signInUser.handler
    events:
      - httpApi:
          path: '/api/signin'
          method: POST
  postNewQuiz:
    handler: src/functions/postNewQuiz.handler
    events:
      - httpApi:
          path: '/api/quiz'
          method: POST
  getAllQuizes:
    handler: src/functions/getAllQuizes.handler
    events:
      - httpApi:
          path: '/api/quiz'
          method: GET
  getQuiz:
    handler: src/functions/getQuiz.handler
    events:
      - httpApi:
          path: '/api/quiz/{quizId}'
          method: GET
  postAdditionalQuestionsToQuiz:
    handler: src/functions/postAdditionalQuestionsToQuiz.handler
    events:
      - httpApi:
          path: '/api/quiz/{quizId}'
          method: PATCH

resources:
  Resources:
    QuizUsersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QuizUsersDb
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: userNameIndex
            KeySchema:
              - AttributeName: userName
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    QuizTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QuizTable
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
          - AttributeName: creatorId
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: creatorIDIndex
            KeySchema:
              - AttributeName: creatorId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    questionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: questionTable
        AttributeDefinitions:
          - AttributeName: questionId
            AttributeType: S
          - AttributeName: quizId
            AttributeType: S
        KeySchema:
          - AttributeName: questionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: quizIdIndex
            KeySchema:
              - AttributeName: quizId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
