service: quiztopia-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  profile: ${env:PROFILE}
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct
  environment:
    DYNAMODB_USERS_TABLE: QuizUsersDb
    DYNAMODB_USER_INDEX: userNameIndex
    DYNAMODB_REGION: 'eu-north-1'
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

package:
  individually: true

functions:
  signUpUser:
    handler: src/functions/user/signUpUser.handler
    events:
      - httpApi:
          path: '/api/signup'
          method: POST
  signInUser:
    handler: src/functions/user/signInUser.handler
    events:
      - httpApi:
          path: '/api/signin'
          method: POST
  # getAllQuiz:
  #   handler: src/functions/getAllQuiz/index.handler
  #   events:
  #     - httpApi:
  #         path: '/api/quiz/'
  #         method: GET

resources:
  Resources:
    QuizUsersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QuizUsersDb
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: userNameIndex
            KeySchema:
              - AttributeName: userName
                KeyType: HASH
            Projection:
              ProjectionType: ALL
