service: quiztopia-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  profile: ${env:PROFILE}
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct
  environment:
    DYNAMODB_USERS_TABLE: QuizUsersDb
    DYNAMODB_USER_INDEX: userNameIndex
    DYNAMODB_QUIZ_TABLE: QuizTable
    DYNAMODB_CREATOR_INDEX: creatorIDIndex
    DYNAMODB_QUESTION_TABLE: questionTable
    DYNAMODB_QUESTION_INDEX: quizIdIndex
    DYNAMODB_LEADERBOARD_TABLE: LeaderboardTable
    DYNAMODB_REGION: 'eu-north-1'
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

package:
  individually: true

functions:
  - ${file(src/yaml/userFunctions.yml)}
  - ${file(src/yaml/quizFunctions.yml)}
  - ${file(src/yaml/leaderboardFunctions.yml)}

resources: ${file(src/yaml/dynamoResources.yml)}
